title: "NotNekodev Website"
discord: "Personal website :3"

author:
  name: "Nekodev"

plugins:
  - jekyll-seo-tag

remote_theme: just-the-docs/just-the-docs

  
color_scheme: dark

url: "https://notnekodev.github.io/"

search_enabled: true
