title: "NotNekodev"
description: "Personal website"

author:
  name: "NotNekodev"

remote_theme: "jekyll/minima"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark
  social_links:
    - title: "GitHub"
      icon: github
      url: "https://github.com/NotNekodev"

url: "https://notnekodev.github.io"
